instrumentation:
    root: lib
    extensions:
        - .js
    default-excludes: true
    excludes: ['**/injections/**', '**/util/sauce.js']

reporting:
    reports:
        - lcov
    dir: ./lib/coverage