language: node_js

script:
  - ./node_modules/.bin/magellan --external_build_id=$TRAVIS_BUILD_ID --sauce --bail_time=${MAGELLAN_INDIVIDUAL_TEST_BAIL_TIME} --max_workers=${MAGELLAN_MAX_WORKERS} --browsers=${TIER_1_2_BROWSERS} --nightwatch_config tests/conf/nightwatch.json

env:
  - TIER_1_2_BROWSERS=microsoftedge_14_Windows_10_Desktop,safari_10_OS_X_10_11_Desktop,IE_11_Windows_10_Desktop,safari_9_OS_X_10_11_Desktop,IE_11_Windows_10_Desktop,IE_10_Windows_2012_Desktop,firefox_50_Windows_2012_R2_Desktop

node_js:
  - v7
  - v6
  - v5
  - v4

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  # ensure latest npm installed.
  - npm install -g npm
  - npm --version
  - export MAGELLAN_BUILD_NAME=${TRAVIS_JOB_ID}_${TRAVIS_JOB_NUMBER}
  - export MAGELLAN_BUILD_ID=`date +%s`
  - export SAUCE_TUNNEL_ID=${TRAVIS_JOB_ID}_${TRAVIS_JOB_NUMBER}


